# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=200)),
                ('taobao_sales', models.IntegerField(default=0)),
                ('taobao_total_sales', models.IntegerField(default=0)),
                ('jd_sales', models.IntegerField(default=0)),
                ('jd_total_sales', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('view', models.IntegerField(default=0)),
                ('visitor', models.IntegerField(default=0)),
                ('payment', models.FloatField(default=0.0)),
                ('number', models.IntegerField(default=0)),
                ('buyer', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_error', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('week', models.DateField()),
                ('table', models.CharField(max_length=200)),
                ('operator', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('week', models.DateField()),
                ('agent_name', models.CharField(blank=True, max_length=200)),
                ('agent_type', models.CharField(blank=True, max_length=200)),
                ('pick_up', models.IntegerField(default=0)),
                ('sales_online', models.IntegerField(default=0)),
                ('sales_offline', models.IntegerField(default=0)),
                ('sales_offline_count', models.IntegerField(default=0)),
                ('inventory_first', models.IntegerField(default=0)),
                ('inventory_lower', models.IntegerField(default=0)),
                ('reject', models.IntegerField(default=0)),
                ('is_native', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('baidu_index', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.IntegerField(default=0)),
                ('active_user', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('active_user', models.IntegerField(default=0)),
                ('active_rate', models.FloatField(default=0.0)),
                ('new_user', models.IntegerField(default=0)),
                ('new_rate', models.FloatField(default=0.0)),
                ('launch_data', models.IntegerField(default=0)),
                ('launch_rate', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('is_native', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
