# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_salesstatus_agent_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('fans', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
