# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_mediafan_fans_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafan',
            old_name='fans_total',
            new_name='fans_increment',
        ),
    ]
