# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_taobaodetail_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbroadSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('comment', models.IntegerField(default=0)),
                ('total_comment', models.IntegerField(default=0)),
                ('site', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('google_index', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_group_id', models.CharField(blank=True, max_length=200)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('version', models.CharField(blank=True, max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('device', models.IntegerField(default=0)),
                ('count_per_launch', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
