# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20170225_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTagContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),

    ]
