# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_auto_20170302_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaTagContent',
            new_name='MediaTag',
        ),
    ]
