# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_auto_20170302_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediatag',
            old_name='quantity',
            new_name='count',
        ),
        migrations.CreateModel(
            name='GlobalElectronicSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(default='insta360 Nano', max_length=200)),
                ('country', models.CharField(default='\u4e2d\u56fd', max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('comment', models.IntegerField(default=0)),
                ('sale', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('version', models.CharField(blank=True, max_length=200)),
                ('success_count', models.IntegerField(default=0)),
                ('success_device', models.IntegerField(default=0)),
                ('success_count_per_launch', models.FloatField(default=0.0)),
                ('try_count', models.IntegerField(default=0)),
                ('try_device', models.IntegerField(default=0)),
                ('try_count_per_launch', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('version', models.CharField(blank=True, max_length=200)),
                ('img_count', models.IntegerField(default=0)),
                ('img_device', models.IntegerField(default=0)),
                ('img_count_per_launch', models.FloatField(default=0.0)),
                ('video_count', models.IntegerField(default=0)),
                ('video_device', models.IntegerField(default=0)),
                ('video_count_per_launch', models.FloatField(default=0.0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AbroadSales',
        ),
        migrations.AddField(
            model_name='errorcondition',
            name='error_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='errorcondition',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
        migrations.AddField(
            model_name='sharechannel',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
        migrations.AddField(
            model_name='sharemode',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
        migrations.AddField(
            model_name='usecondition',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
        migrations.AddField(
            model_name='userdistribution',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
    ]
