# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_auto_20170302_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecount',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
        migrations.AddField(
            model_name='takecount',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
    ]
