# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_auto_20170306_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharechannel',
            name='channel',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sharechannel',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
