# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0015_auto_20170406_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharechannel',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
