# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_auto_20170406_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsales',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
