# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_auto_20170412_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsales',
            name='commodity',
            field=models.CharField(max_length=200),
        ),
    ]
