# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0019_auto_20170412_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsales',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
        migrations.AddField(
            model_name='salesstatus',
            name='product',
            field=models.CharField(default='nano', max_length=200),
        ),
    ]
