# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0020_auto_20170415_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meltwater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('type', models.CharField(default='social', max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
