# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0021_meltwater'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoukuData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('comment', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=200)),
                ('thumb', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('published_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
