# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0023_auto_20170429_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
