# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0024_auto_20170429_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='nano', max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('view', models.IntegerField(default=0)),
                ('visitor', models.IntegerField(default=0)),
                ('customer', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='nano', max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('show', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=0)),
                ('turnover', models.FloatField(default=0.0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
