# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0025_accessdata_electronicpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fBuyPri', models.FloatField(default=0.0)),
                ('mBuyPri', models.FloatField(default=0.0)),
                ('mSellPri', models.FloatField(default=0.0)),
                ('update', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
