# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0026_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='bankConversionPri',
            field=models.FloatField(default=0.0),
        ),
    ]
