# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0027_exchangerate_bankconversionpri'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('group_id', models.CharField(max_length=200)),
                ('group_name', models.CharField(max_length=200)),
                ('member_count', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('is_native', models.IntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
