# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0028_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsales',
            name='ext_sales',
            field=models.IntegerField(default=0),
        ),
    ]
