# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.IntegerField(max_length=200)),
                ('active_user', models.IntegerField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
