# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstatus',
            name='agent_price',
            field=models.IntegerField(default=0),
        ),
    ]
