# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_competitorsales_searchindex_userdistribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecondition',
            old_name='activeUser',
            new_name='active_user',
        ),
        migrations.RenameField(
            model_name='usecondition',
            old_name='newUser',
            new_name='new_user',
        ),
        migrations.RenameField(
            model_name='userdistribution',
            old_name='activeUser',
            new_name='active_user',
        ),
    ]
