# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20160810_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorsales',
            name='taobao_sales',
        ),
        migrations.RemoveField(
            model_name='competitorsales',
            name='taobao_total_sales',
        ),
        migrations.RemoveField(
            model_name='searchindex',
            name='baidu_index',
        ),
        migrations.RemoveField(
            model_name='usecondition',
            name='active_user',
        ),
        migrations.RemoveField(
            model_name='usecondition',
            name='new_user',
        ),
        migrations.RemoveField(
            model_name='userdistribution',
            name='active_user',
        ),
        migrations.RemoveField(
            model_name='userdistribution',
            name='is_native',
        ),
    ]
