# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20160810_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsales',
            name='taobao_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitorsales',
            name='taobao_total_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='baidu_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usecondition',
            name='active_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usecondition',
            name='new_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdistribution',
            name='active_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdistribution',
            name='is_native',
            field=models.IntegerField(default=0),
        ),
    ]
