# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20160928_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafan',
            name='fans_total',
            field=models.IntegerField(default=0),
        ),
    ]
