# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20160810_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('view', models.IntegerField(default=0)),
                ('visitor', models.IntegerField(default=0)),
                ('payment', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('buyer', models.IntegerField(default=0)),
                ('conversion', models.CharField(max_length=200)),
                ('per_ticket_sales', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('pick_up', models.IntegerField(default=0)),
                ('sales_online', models.IntegerField(default=0)),
                ('sales_offline', models.IntegerField(default=0)),
                ('inventory_first', models.IntegerField(default=0)),
                ('inventory_lower', models.IntegerField(default=0)),
                ('reject', models.DateTimeField(auto_now_add=True)),
                ('is_native', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
