# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_electronicsales_salesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsales',
            name='week',
            field=models.DateField(),
        ),
    ]
