# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20160811_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsales',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesstatus',
            name='week',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='searchindex',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usecondition',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userdistribution',
            name='date',
            field=models.DateField(),
        ),
    ]
