# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_taobaodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='taobaodetail',
            name='commodity',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
