# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_auto_20160811_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesstatus',
            name='reject',
            field=models.IntegerField(default=0),
        ),
    ]
