# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20160812_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicsales',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='electronicsales',
            name='per_ticket_sales',
        ),
    ]
