# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20160813_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_error', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
