# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_errorcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecondition',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
