# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_auto_20160816_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistribution',
            name='active_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userdistribution',
            name='install_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userdistribution',
            name='install_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdistribution',
            name='new_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userdistribution',
            name='new_user',
            field=models.IntegerField(default=0),
        ),
    ]
