# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_auto_20160817_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdistribution',
            old_name='install_user',
            new_name='launch_data',
        ),
        migrations.RenameField(
            model_name='userdistribution',
            old_name='install_rate',
            new_name='launch_rate',
        ),
    ]
