# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_auto_20160817_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsales',
            name='jd_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitorsales',
            name='jd_total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
