# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0015_auto_20160818_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('week', models.DateField()),
                ('table', models.CharField(max_length=200)),
                ('operator', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
