# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_auto_20160823_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstatus',
            name='agent_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesstatus',
            name='agent_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesstatus',
            name='sales_offline_count',
            field=models.IntegerField(default=0),
        ),
    ]
